<?php
/**
 * @file
 * Code for the GSB Feature PhD Candidate CT feature.
 */

include_once 'gsb_feature_phd_candidate_ct.features.inc';

/**
 * Implements hook_form_alter().
 */
function gsb_feature_phd_candidate_ct_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'phd_candidate_node_form') {

    $language = $form['language']['#value'];

    foreach ($form['field_working_papers'][$language] as $key => &$value) {
      if (!is_int($key)) {
        continue;
      }
      unset($form['field_working_papers'][$language][$key]['field_link_single'][$language][0]['#title']);
    }

    foreach ($form['field_work_in_progress'][$language] as $key => &$value) {
      if (!is_int($key)) {
        continue;
      }
      unset($form['field_work_in_progress'][$language][$key]['field_link_single'][$language][0]['#title']);
    }   

    foreach ($form['field_publications'][$language] as $key => &$value) {
      if (!is_int($key)) {
        continue;
      }
      unset($form['field_publications'][$language][$key]['field_link_single'][$language][0]['#title']);
    }

    foreach ($form['field_link_single'][$language] as $key => &$value) {
      if (!is_int($key)) {
        continue;
      }
      unset($form['field_link_single'][$language][$key]['#title']);
    } 

    foreach ($form['field_working_papers'][$language] as $key => &$value) {
      if (!is_int($key)) {
        continue;
      }
      unset($form['field_working_papers'][$language][$key]['field_title']);  
    } 

    $form['field_academic_institution'][$language][0]['value']['#states'] = array(
      'visible' => array(
        ':input[name="field_job_display[' . $language . ']"]' => array(
          array('value' => 'placement_page'),
        ),
      ),
    ); 

    $form['field_year']['#states'] = array(
      'visible' => array(
        ':input[name="field_job_display[' . $language . ']"]' => array(
          array('value' => 'placement_page'),
        ),
      ),
    ); 

  } 

}

